services:
  # Backend API Service
  - type: web
    name: perplexcipe-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend.api.main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: PERPLEXCIPE_PERPLEXITY_API_KEY
        sync: false

  # Frontend Service
  - type: web
    name: perplexcipe-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 