services:
  - type: web
    name: perplexcipe-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend.api.main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: PERPLEXCIPE_PERPLEXITY_API_KEY
        sync: false 