services:
  # Backend API Service
  - type: web
    name: perplexcipe
    env: node
    buildCommand: |
      cd frontend
      npm install
      npm run build
      cd ../backend
      pip install -r requirements.txt
    startCommand: |
      cd backend
      gunicorn api.main:app
    staticPublishPath: ./frontend/build
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: PERPLEXCIPE_PERPLEXITY_API_KEY
        sync: false
      - key: REACT_APP_API_URL
        value: https://perplexcipe.onrender.com

  # Frontend Service
  - type: web
    name: perplexcipe-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 